# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9fz6JmB3Wk_yL669jXJ3nyE71h-sPCm
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    DataCollatorWithPadding,
    TrainingArguments,
    Trainer,
)
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report
import gradio as gr

# ------------------------------------------------------------
# 1. Load dataset
# ------------------------------------------------------------
banking_raw = load_dataset("banking77")

# ------------------------------------------------------------
# 2. Select top 10 intent classes
# ------------------------------------------------------------
train_df = pd.DataFrame(banking_raw["train"])
top_10_intents = train_df["label"].value_counts().head(10).index.tolist()

def filter_top_10(example):
    return example["label"] in top_10_intents

train_dataset = banking_raw["train"].filter(filter_top_10)
test_dataset = banking_raw["test"].filter(filter_top_10)

label_map = {old_label: new_label for new_label, old_label in enumerate(top_10_intents)}

def remap_labels(example):
    example["label"] = label_map[example["label"]]
    return example

train_dataset = train_dataset.map(remap_labels)
test_dataset = test_dataset.map(remap_labels)

split = train_dataset.train_test_split(test_size=0.2, seed=42)
train_dataset = split["train"]
val_dataset = split["test"]

# ------------------------------------------------------------
# 3. Tokenization
# ------------------------------------------------------------
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(example):
    return tokenizer(example["text"], truncation=True)

tokenized_train = train_dataset.map(tokenize_function, batched=True)
tokenized_val = val_dataset.map(tokenize_function, batched=True)

tokenized_train = tokenized_train.remove_columns(["text"])
tokenized_val = tokenized_val.remove_columns(["text"])

tokenized_train.set_format("torch")
tokenized_val.set_format("torch")

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

# ------------------------------------------------------------
# 4. Label names
# ------------------------------------------------------------
original_label_names = banking_raw["train"].features["label"].names
subset_label_names = [original_label_names[i] for i in top_10_intents]

id2label = {new_id: name for new_id, name in enumerate(subset_label_names)}
label2id = {v: k for k, v in id2label.items()}
num_labels = len(id2label)

# ------------------------------------------------------------
# 5. Model
# ------------------------------------------------------------
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id,
)

# ------------------------------------------------------------
# 6. Metrics
# ------------------------------------------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, preds)
    f1 = f1_score(labels, preds, average="weighted")
    return {"accuracy": acc, "f1": f1}

# ------------------------------------------------------------
# 7. Training
# ------------------------------------------------------------
print("\n" + "=" * 40)
print("Model Training with Hugging Face Trainer")
print("=" * 40)

training_args = TrainingArguments(
    output_dir="./banking_results",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    logging_steps=50,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("\nStarting training...")
trainer.train()

print("\nFinal evaluation metrics on validation set:")
eval_metrics = trainer.evaluate()
for k, v in eval_metrics.items():
    if isinstance(v, (int, float, np.floating)):
        print(f"{k}: {v:.4f}")
    else:
        print(f"{k}: {v}")

# ------------------------------------------------------------
# 8. Validation predictions
# ------------------------------------------------------------
pred_output = trainer.predict(tokenized_val)
logits = pred_output.predictions
labels = pred_output.label_ids
preds = np.argmax(logits, axis=-1)

class_names = [id2label[i] for i in range(len(id2label))]
cm = confusion_matrix(labels, preds)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)
plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix – Banking Intents")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print("\nClassification Report:")
print(classification_report(labels, preds, target_names=class_names, digits=4))

# ------------------------------------------------------------
# 9. Example prediction review
# ------------------------------------------------------------
device = model.device

def predict_intent(input_text, top_k=3):
    model.eval()

    encoded = tokenizer(
        input_text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=64,
    )
    encoded = {k: v.to(device) for k, v in encoded.items()}

    with torch.no_grad():
        outputs = model(**encoded)

    probabilities = torch.softmax(outputs.logits, dim=-1)[0]
    top_probs, top_ids = torch.topk(probabilities, k=top_k)

    results = []
    for score, label_id in zip(top_probs, top_ids):
        results.append((id2label[int(label_id)], float(score)))
    return results

sample_query = "My card was swallowed by the ATM and I need help."
print("\nSample query:", sample_query)
print("Top predicted intents:")
for label, score in predict_intent(sample_query):
    print(f"- {label}: {score:.4f}")

# ------------------------------------------------------------
# 10. Gradio demo
# ------------------------------------------------------------
def gradio_predict(query):
    results = predict_intent(query, top_k=3)
    return "\n".join([f"{label}: {score:.4f}" for label, score in results])

demo = gr.Interface(
    fn=gradio_predict,
    inputs=gr.Textbox(lines=2, placeholder="Enter a banking support query..."),
    outputs=gr.Textbox(lines=5),
    title="Banking Intent Classification Demo",
    description="Prototype system for classifying banking customer support queries into likely intent categories."
)

demo.launch(share=True)